### ISSUE TITLE
TrollStore not Installing

### ISSUE THREAD

**Issue by LucasIsRed** [straight-tamago/misakaX#200]
It says it was installed, but I can't find the Trollstore app. Here are the logs:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at iPhone.ExecuteProcess(String fileName, String arguments, String workingDir)
   at iPhone.GetPymobiledevice3Version()
   at misakaX.MainWindow.<<-ctor>b__11_1>d.MoveNext()File copied successfully to C:\Users\redacted\Downloads\misakaX-2.2-windows-edition\data/tmp.plist.
iOS Version: 18.0
iOS Name: iPhone 15 Pro Max
Downloading... [https://github.com/opa334/TrollStore/releases/latest/download/PersistenceHelper_Embedded]
Installing...
[Restore] C:\Users\redacted\Downloads\misakaX-2.2-windows-edition\data/sparserestore/PersistenceHelper_Embedded -> /var/containers/Bundle/Application/95BB0549-C2A0-4062-B7C0-220438D795B6/Tips.app/Tips
Installed TrollStore
Success. Rebooting your device...
Remember to turn Find My back on!

**Comment by ridhoperdana** [comment]
trollstore is on Tips app

**Comment by jmaracorda** [comment]
not opening the tips app

**Comment by jmaracorda** [comment]
it kept closing

**Comment by RJMultiDev** [comment]
on ios17.6+ apple changed roothelper so TrollStore will stop work!

**Comment by Svetrikk** [comment]
How can I uninstall it? I accidentally pressed on install and the tips app is now crashing

**Comment by RJMultiDev** [comment]
> How can I uninstall it? I accidentally pressed on install and the tips app is now crashing

emmm try uninstall Tips directly and reinstall it from App Store?
