### ISSUE TITLE
troll store

### ISSUE THREAD

**Issue by hossein79211** [straight-tamago/misakaX#272]
hi
i tried to install troll store 

it says successful and the phone restart but it dosnt install troll store

**Comment by hossein79211** [comment]
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at iPhone.ExecuteProcess(String fileName, String arguments, String workingDir)
   at iPhone.GetPymobiledevice3Version()
   at misakaX.MainWindow.<<-ctor>b__11_1>d.MoveNext()File copied successfully to C:\Users\hossein\Desktop\iphone mod\data/tmp.plist.
iOS Version: 18.1
iOS Name: iPhone 12
Downloading... [https://github.com/opa334/TrollStore/releases/latest/download/PersistenceHelper_Embedded]
Installing...
[Restore] C:\Users\hossein\Desktop\iphone mod\data/sparserestore/PersistenceHelper_Embedded -> /var/containers/Bundle/Application/D8B568A1-8032-45E2-8185-72D6AF13D8DB/Tips.app/Tips
Installed TrollStore
Success. Rebooting your device...
Remember to turn Find My back on!

**Comment by Cansavural** [comment]
Go to Tips app and click Install Trollstore..

**Comment by hossein79211** [comment]
> Go to Tips app and click Install Trollstore..

i cant open the tips app it crash

**Comment by Irrucky** [comment]
Hello, I also encountered the same problem, have you solved it? My system is ios17.5

**Comment by Irrucky** [comment]
> > Go to Tips app and click Install Trollstore..
> 
> 
> 
> i cant open the tips app it crash

Hello, I also encountered the same problem, have you solved it? My system is ios17.5
