### ISSUE TITLE
Unknown error,please check log

### ISSUE THREAD

**Issue by Zackerychou** [straight-tamago/misakaX#282]
[Restore] F:\2.2\data/sparserestore/eligibility.plist -> /var/db/eligibilityd/eligibility.plist
Traceback (most recent call last):
  File "F:\2.2\data\python-3.12.5-embed-amd64\Lib\site-packages\pymobiledevice3\usbmux.py", line 167, in create_usbmux_socket
    return SafeStreamSocket(address, family)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\2.2\data\python-3.12.5-embed-amd64\Lib\site-packages\pymobiledevice3\usbmux.py", line 111, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\2.2\data\sparserestore\restore.py", line 87, in <module>
    main()
  File "F:\2.2\data\sparserestore\restore.py", line 31, in main
    for device in usbmux.list_devices():
                  ^^^^^^^^^^^^^^^^^^^^^
  File "F:\2.2\data\python-3.12.5-embed-amd64\Lib\site-packages\pymobiledevice3\usbmux.py", line 410, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\2.2\data\python-3.12.5-embed-amd64\Lib\site-packages\pymobiledevice3\usbmux.py", line 406, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\2.2\data\python-3.12.5-embed-amd64\Lib\site-packages\pymobiledevice3\usbmux.py", line 174, in create
    sock = MuxConnection.create_usbmux_socket(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\2.2\data\python-3.12.5-embed-amd64\Lib\site-packages\pymobiledevice3\usbmux.py", line 169, in create_usbmux_socket
    raise ConnectionFailedToUsbmuxdError()
pymobiledevice3.exceptions.ConnectionFailedToUsbmuxdError

PLEASE HELP ME!! I've been stuck here for a whole dayT T

**Comment by DiegoMA2901** [comment]
We're waiting misaka x to release a new version that works with the new iOS 18.1 beta 5 or beta 2

**Comment by sohan028** [comment]
bro you solve this error 
ya still have problem if you solve this then tell me how you solve this

**Comment by Zackerychou** [comment]
> bro you solve this error ya still have problem if you solve this then tell me how you solve this

sorry...I gave up lol
