### ISSUE TITLE
Error with windows 10 2.2

### ISSUE THREAD

**Issue by forestg10** [straight-tamago/misakaX#283]
I'm trying to use windows 10 2.2 and 2.1 and nothing applies. I've tried using pip to install Pymobiledevice3 and still nothing works.

System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at iPhone.ExecuteProcess(String fileName, String arguments, String workingDir)
   at iPhone.GetPythonVersion()
   at misakaX.MainWindow.<<-ctor>b__11_1>d.MoveNext()

**Comment by simioni21** [comment]
what's the ios version you're using?

**Comment by rajb16** [comment]
This happens to me as well. Im using ios 17.2

**Comment by forestg10** [comment]
same a 12 17.2

**Comment by mrcarman7** [comment]
It said that for me but I was using iOS 18

**Comment by simioni21** [comment]
> same a 12 17.2
> 
> 

maybe its the IOS version, but idk, i would try to update the phone to ios18

**Comment by mrcarman7** [comment]
does anyone have an answer

**Comment by forestg10** [comment]
It's an iPad and I'm not updating

**Comment by forestg10** [comment]
It's not the iOS version because it doesn't work on my phone either a12 16.6.1. I experienced what others have where it works once and the en it breaks.

**Comment by mrcarman7** [comment]
I am going to try redownloading misaka X on windows

**Comment by mrcarman7** [comment]
Is it a file?

**Comment by mrcarman7** [comment]
does someone know how to fix it

**Comment by spovondra** [comment]
Try "pip install Pymobiledevice3"

**Comment by forestg10** [comment]
> Try "pip install Pymobiledevice3"

I LITERALLY SAID I TRIED THAT

**Comment by Dragon10650** [comment]
try "pip install Pymobiledevice" without 3
