### ISSUE TITLE
How do i fix this errpr

### ISSUE THREAD

**Issue by Waffles364** [straight-tamago/misakaX#383]
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at iPhone.ExecuteProcess(String fileName, String arguments, String workingDir)
   at iPhone.GetPythonVersion()
   at misakaX.MainWindow.<<-ctor>b__11_1>d.MoveNext()
can anyone find a solution to fix this?

**Comment by Yu1hen** [comment]
同样的问题
